attn_dim: 512
beam_width: 5
bidirectional: false
dec_dim: 512
decode_type: beamsearch
dropout: 0.1
emb_dim: 80
enc_dim: 256
enc_type: conv_row_encoder
eos_id: 2
log_step: 100
log_text: false
lr: 0.01
n_class: 520
num_layers: 1
sos_id: 1
text: !!python/object:image2latex.text.Text100k
  TOKENIZE_PATTERN: !!python/object/apply:re._compile
  - (\\[a-zA-Z]+)|((\\)*[$-/:-?{-~!"^_`\[\]])|(\w)|(\\)
  - 32
  eos_id: 2
  id2word:
  - <p>
  - <s>
  - <e>
  - \coprod
  - \dag
  - \dagger
  - \leftarrow
  - \nearrow
  - \succeq
  - \protecte
  - \textnormal
  - H
  - '='
  - \top
  - \asymp
  - \hrule
  - \textstyle
  - \nabla
  - \vec
  - \overwithdelims
  - \omega
  - \Biggm
  - \setcounter
  - D
  - \scriptstyle
  - o
  - \expandafter
  - \bar
  - '0'
  - \renewcommand
  - \symbol
  - \nulldelimiterspace
  - \smallint
  - \setlength
  - \sp
  - \dotfill
  - '['
  - \slash
  - \jmath
  - \{
  - \Biggr
  - \arrowvert
  - \land
  - '2'
  - N
  - \brace
  - \Theta
  - \noalign
  - \end
  - \textbf
  - \epsilon
  - S
  - \skew
  - \normalsize
  - \right
  - \imath
  - \to
  - \lefteqn
  - \bullet
  - \Sigma
  - \lambda
  - \circle
  - \emptyset
  - \raisebox
  - \kern
  - \vskip
  - \neq
  - \biggl
  - \not
  - \sl
  - \cdotp
  - \SS
  - \tiny
  - \widetilde
  - \varphi
  - \|
  - \cline
  - \large
  - \special
  - '3'
  - \bigsqcup
  - \mathbf
  - '"'
  - \smile
  - d
  - \c
  - \-
  - <
  - \*
  - \xi
  - \parbox
  - \leavevmode
  - '>'
  - \prime
  - a
  - M
  - \ni
  - \quad
  - \langle
  - ','
  - \mathversion
  - m
  - \times
  - '}'
  - \O
  - \left
  - \vert
  - \vrule
  - \Longleftarrow
  - \leq
  - \in
  - \preceq
  - \everymath
  - \atop
  - \bigtriangleup
  - \upsilon
  - \multicolumn
  - \Downarrow
  - \m
  - \tt
  - \sharp
  - \vspace
  - F
  - \relax
  - \protectm
  - \le
  - \big
  - \;
  - \rbrack
  - J
  - \do
  - \varrho
  - \sc
  - q
  - \downarrow
  - \footnotemark
  - \textsf
  - \raise
  - \mp
  - \ae
  - c
  - \Bigr
  - \cap
  - \footnote
  - /
  - \^
  - \mathnormal
  - +
  - e
  - \mapsto
  - \vphantom
  - \exists
  - \ss
  - \Bigl
  - \,
  - \mathopen
  - \}
  - \ell
  - \longleftarrow
  - \varsigma
  - \ominus
  - K
  - \ddag
  - \sqcap
  - \bigwedge
  - \thinspace
  - \Psi
  - \longleftrightarrow
  - \overleftarrow
  - \propto
  - \o
  - \nolinebreak
  - G
  - '&'
  - \geq
  - B
  - \rightleftharpoons
  - \textup
  - \surd
  - \rceil
  - \Lambda
  - \ensuremath
  - \chi
  - \ref
  - \bigg
  - \brack
  - '{'
  - \ast
  - \rightharpoonup
  - \psi
  - \it
  - \mit
  - \eta
  - \sf
  - \aleph
  - '`'
  - \notin
  - \rgroup
  - \diamond
  - \ldots
  - R
  - \"
  - j
  - \wedge
  - \bmod
  - \Omega
  - \ddots
  - \gg
  - \swarrow
  - \equiv
  - \small
  - \AA
  - \&
  - k
  - \strut
  - _
  - \Gamma
  - \oslash
  - '1'
  - \vss
  - \ointop
  - \gamma
  - \hline
  - \smallskip
  - \makebox
  - \rho
  - \ll
  - \huge
  - \arraycolsep
  - \hphantom
  - p
  - \newcommand
  - \framebox
  - \overbrace
  - \vcenter
  - \label
  - \vline
  - \forall
  - \scriptscriptstyle
  - \protectu
  - \setminus
  - \bigcup
  - \llap
  - \rangle
  - \pi
  - \sim
  - \tau
  - \mid
  - \bigtriangledown
  - \infty
  - \j
  - \mathcal
  - \(
  - \thicklines
  - \triangleright
  - \emph
  - \vee
  - i
  - V
  - \Delta
  - \lbrace
  - \Bigg
  - \longrightarrow
  - \parallel
  - \lgroup
  - ''''
  - \smash
  - \mathstrut
  - \prod
  - \Leftrightarrow
  - \check
  - \verb
  - \dots
  - \hbar
  - \varepsilon
  - \Vert
  - \natural
  - \bigoplus
  - \uparrow
  - \protectZ
  - r
  - \dot
  - \'
  - \bigcap
  - v
  - \i
  - \vector
  - \cite
  - \approx
  - \Rightarrow
  - \breve
  - \textit
  - \rlap
  - \fboxsep
  - \binom
  - \mathrm
  - E
  - \prec
  - \pm
  - (
  - \cong
  - \succ
  - \nonumber
  - \begin
  - \footnotesize
  - '5'
  - \phantom
  - \bot
  - \kappa
  - \line
  - \linethickness
  - \Bigm
  - \lq
  - \oint
  - \colon
  - \rightarrowfill
  - \bigm
  - \sqrt
  - \unitlength
  - \zeta
  - \odot
  - '4'
  - \space
  - g
  - \otimes
  - \Re
  - \Biggl
  - \oval
  - '-'
  - '*'
  - \ddot
  - \pounds
  - A
  - l
  - \tilde
  - \biggm
  - \acute
  - \simeq
  - Y
  - \mskip
  - \mathsf
  - \mu
  - \sqcup
  - T
  - \leftrightarrow
  - \null
  - \flat
  - \sum
  - Q
  - \hspace
  - \bigskip
  - '|'
  - '?'
  - \supseteq
  - \atopwithdelims
  - ^
  - X
  - ':'
  - \Large
  - \texttt
  - \enskip
  - \longmapsto
  - z
  - \tabcolsep
  - \mathop
  - \sigma
  - \wp
  - \Huge
  - \)
  - .
  - h
  - )
  - '6'
  - y
  - \iota
  - \P
  - \textcircled
  - \frac
  - \subset
  - \mathit
  - \cup
  - \underbrace
  - \int
  - \phi
  - \hat
  - \doteq
  - \Upsilon
  - \grave
  - \!
  - \star
  - \circ
  - \
  - \qquad
  - \alpha
  - w
  - \em
  - O
  - \Big
  - \overrightarrow
  - \nu
  - \arraystretch
  - \cdot
  - \mathclose
  - \hfil
  - '7'
  - \overline
  - ;
  - \delta
  - \lceil
  - \crcr
  - \triangleleft
  - \mathord
  - \rbrace
  - \theta
  - \d
  - \vartheta
  - '9'
  - \buildrel
  - \cal
  - \partial
  - \unboldmath
  - \Phi
  - \displaystyle
  - '8'
  - \pmod
  - \supset
  - L
  - \ooalign
  - \diamondsuit
  - '\:'
  - \underline
  - \[
  - \protect
  - \fill
  - U
  - \itshape
  - \widehat
  - \_
  - \textrm
  - \sb
  - \uppercase
  - \enspace
  - \lfloor
  - f
  - \multiput
  - s
  - Z
  - \hskip
  - \Longrightarrow
  - I
  - \bigl
  - \beta
  - \mathbin
  - \bigr
  - \root
  - C
  - \searrow
  - \of
  - \romannumeral
  - \b
  - \/
  - \mathrel
  - \Im
  - \fbox
  - \subseteq
  - \ne
  - \bigcirc
  - \bigvee
  - \rfloor
  - \vdots
  - \vdash
  - \triangle
  - \ddagger
  - P
  - \Longleftrightarrow
  - \hfill
  - \stackrel
  - \protectE
  - \scshape
  - \operatorname
  - '!'
  - \varpi
  - \cdots
  - \def
  - \mathaccent
  - \lbrack
  - \oplus
  - \ge
  - \amalg
  - W
  - ']'
  - \Pi
  - \boldmath
  - \hookrightarrow
  - \backslash
  - \lower
  - '~'
  - \L
  - \bf
  - \bigotimes
  - x
  - \biggr
  - t
  - n
  - \scriptsize
  - \Xi
  - \hss
  - \S
  - \medskip
  - b
  - \mathtt
  - \LARGE
  - \mkern
  - \]
  - \put
  - \perp
  - \rightarrow
  - \l
  - u
  - \qbezier
  n_class: 520
  pad_id: 0
  sos_id: 1
  word2id:
    '!': 480
    '"': 82
    '&': 173
    '''': 265
    (: 299
    ): 371
    '*': 329
    +: 147
    ',': 99
    '-': 328
    .: 369
    /: 144
    '0': 28
    '1': 218
    '2': 43
    '3': 79
    '4': 321
    '5': 305
    '6': 372
    '7': 404
    '8': 423
    '9': 416
    ':': 357
    ;: 406
    <: 87
    <e>: 2
    <p>: 0
    <s>: 1
    '=': 12
    '>': 92
    '?': 352
    A: 332
    B: 175
    C: 455
    D: 23
    E: 296
    F: 122
    G: 172
    H: 11
    I: 449
    J: 129
    K: 161
    L: 426
    M: 95
    N: 44
    O: 396
    P: 473
    Q: 348
    R: 200
    S: 51
    T: 343
    U: 434
    V: 258
    W: 489
    X: 356
    Y: 338
    Z: 446
    '[': 36
    \: 391
    \!: 388
    \": 201
    \&: 212
    \': 282
    \(: 252
    \): 368
    \*: 88
    \,: 154
    \-: 86
    \/: 460
    '\:': 429
    \;: 127
    \AA: 211
    \Big: 397
    \Bigg: 261
    \Biggl: 326
    \Biggm: 21
    \Biggr: 40
    \Bigl: 153
    \Bigm: 311
    \Bigr: 141
    \Delta: 259
    \Downarrow: 117
    \Gamma: 216
    \Huge: 367
    \Im: 462
    \L: 497
    \LARGE: 511
    \Lambda: 180
    \Large: 358
    \Leftrightarrow: 269
    \Longleftarrow: 108
    \Longleftrightarrow: 474
    \Longrightarrow: 448
    \O: 104
    \Omega: 205
    \P: 375
    \Phi: 421
    \Pi: 491
    \Psi: 166
    \Re: 325
    \Rightarrow: 289
    \S: 507
    \SS: 71
    \Sigma: 59
    \Theta: 46
    \Upsilon: 386
    \Vert: 275
    \Xi: 505
    \[: 431
    \]: 513
    \^: 145
    \_: 437
    \acute: 336
    \ae: 139
    \aleph: 194
    \alpha: 393
    \amalg: 488
    \approx: 288
    \arraycolsep: 228
    \arraystretch: 400
    \arrowvert: 41
    \ast: 187
    \asymp: 14
    \atop: 113
    \atopwithdelims: 354
    \b: 459
    \backslash: 494
    \bar: 27
    \begin: 303
    \beta: 451
    \bf: 498
    \big: 126
    \bigcap: 283
    \bigcirc: 466
    \bigcup: 241
    \bigg: 184
    \biggl: 67
    \biggm: 335
    \biggr: 501
    \bigl: 450
    \bigm: 316
    \bigoplus: 277
    \bigotimes: 499
    \bigr: 453
    \bigskip: 350
    \bigsqcup: 80
    \bigtriangledown: 248
    \bigtriangleup: 114
    \bigvee: 467
    \bigwedge: 164
    \binom: 294
    \bmod: 204
    \boldmath: 492
    \bot: 307
    \brace: 45
    \brack: 185
    \breve: 290
    \buildrel: 417
    \bullet: 58
    \c: 85
    \cal: 418
    \cap: 142
    \cdot: 401
    \cdotp: 70
    \cdots: 482
    \check: 270
    \chi: 182
    \circ: 390
    \circle: 61
    \cite: 287
    \cline: 76
    \colon: 314
    \cong: 300
    \coprod: 3
    \crcr: 409
    \cup: 380
    \d: 414
    \dag: 4
    \dagger: 5
    \ddag: 162
    \ddagger: 472
    \ddot: 330
    \ddots: 206
    \def: 483
    \delta: 407
    \diamond: 198
    \diamondsuit: 428
    \displaystyle: 422
    \do: 130
    \dot: 281
    \doteq: 385
    \dotfill: 35
    \dots: 272
    \downarrow: 134
    \ell: 157
    \em: 395
    \emph: 255
    \emptyset: 62
    \end: 48
    \enskip: 360
    \enspace: 441
    \ensuremath: 181
    \epsilon: 50
    \equiv: 209
    \eta: 192
    \everymath: 112
    \exists: 151
    \expandafter: 26
    \fbox: 463
    \fboxsep: 293
    \fill: 433
    \flat: 346
    \footnote: 143
    \footnotemark: 135
    \footnotesize: 304
    \forall: 237
    \frac: 377
    \framebox: 232
    \gamma: 221
    \ge: 487
    \geq: 174
    \gg: 207
    \grave: 387
    \hat: 384
    \hbar: 273
    \hfil: 403
    \hfill: 475
    \hline: 222
    \hookrightarrow: 493
    \hphantom: 229
    \hrule: 15
    \hskip: 447
    \hspace: 349
    \hss: 506
    \huge: 227
    \i: 285
    \imath: 55
    \in: 110
    \infty: 249
    \int: 382
    \iota: 374
    \it: 190
    \itshape: 435
    \j: 250
    \jmath: 38
    \kappa: 308
    \kern: 64
    \l: 517
    \label: 235
    \lambda: 60
    \land: 42
    \langle: 98
    \large: 77
    \lbrace: 260
    \lbrack: 485
    \lceil: 408
    \ldots: 199
    \le: 125
    \leavevmode: 91
    \left: 105
    \leftarrow: 6
    \lefteqn: 57
    \leftrightarrow: 344
    \leq: 109
    \lfloor: 442
    \lgroup: 264
    \line: 309
    \linethickness: 310
    \ll: 226
    \llap: 242
    \longleftarrow: 158
    \longleftrightarrow: 167
    \longmapsto: 361
    \longrightarrow: 262
    \lower: 495
    \lq: 312
    \m: 118
    \makebox: 224
    \mapsto: 149
    \mathaccent: 484
    \mathbf: 81
    \mathbin: 452
    \mathcal: 251
    \mathclose: 402
    \mathit: 379
    \mathnormal: 146
    \mathop: 364
    \mathopen: 155
    \mathord: 411
    \mathrel: 461
    \mathrm: 295
    \mathsf: 340
    \mathstrut: 267
    \mathtt: 510
    \mathversion: 100
    \medskip: 508
    \mid: 247
    \mit: 191
    \mkern: 512
    \mp: 138
    \mskip: 339
    \mu: 341
    \multicolumn: 116
    \multiput: 444
    \nabla: 17
    \natural: 276
    \ne: 465
    \nearrow: 7
    \neq: 66
    \newcommand: 231
    \ni: 96
    \noalign: 47
    \nolinebreak: 171
    \nonumber: 302
    \normalsize: 53
    \not: 68
    \notin: 196
    \nu: 399
    \null: 345
    \nulldelimiterspace: 31
    \o: 170
    \odot: 320
    \of: 457
    \oint: 313
    \ointop: 220
    \omega: 20
    \ominus: 160
    \ooalign: 427
    \operatorname: 479
    \oplus: 486
    \oslash: 217
    \otimes: 324
    \oval: 327
    \overbrace: 233
    \overleftarrow: 168
    \overline: 405
    \overrightarrow: 398
    \overwithdelims: 19
    \parallel: 263
    \parbox: 90
    \partial: 419
    \perp: 515
    \phantom: 306
    \phi: 383
    \pi: 244
    \pm: 298
    \pmod: 424
    \pounds: 331
    \prec: 297
    \preceq: 111
    \prime: 93
    \prod: 268
    \propto: 169
    \protect: 432
    \protectE: 477
    \protectZ: 279
    \protecte: 9
    \protectm: 124
    \protectu: 239
    \psi: 189
    \put: 514
    \qbezier: 519
    \qquad: 392
    \quad: 97
    \raise: 137
    \raisebox: 63
    \rangle: 243
    \rbrace: 412
    \rbrack: 128
    \rceil: 179
    \ref: 183
    \relax: 123
    \renewcommand: 29
    \rfloor: 468
    \rgroup: 197
    \rho: 225
    \right: 54
    \rightarrow: 516
    \rightarrowfill: 315
    \rightharpoonup: 188
    \rightleftharpoons: 176
    \rlap: 292
    \romannumeral: 458
    \root: 454
    \sb: 439
    \sc: 132
    \scriptscriptstyle: 238
    \scriptsize: 504
    \scriptstyle: 24
    \scshape: 478
    \searrow: 456
    \setcounter: 22
    \setlength: 33
    \setminus: 240
    \sf: 193
    \sharp: 120
    \sigma: 365
    \sim: 245
    \simeq: 337
    \skew: 52
    \sl: 69
    \slash: 37
    \small: 210
    \smallint: 32
    \smallskip: 223
    \smash: 266
    \smile: 83
    \sp: 34
    \space: 322
    \special: 78
    \sqcap: 163
    \sqcup: 342
    \sqrt: 317
    \ss: 152
    \stackrel: 476
    \star: 389
    \strut: 214
    \subset: 378
    \subseteq: 464
    \succ: 301
    \succeq: 8
    \sum: 347
    \supset: 425
    \supseteq: 353
    \surd: 178
    \swarrow: 208
    \symbol: 30
    \tabcolsep: 363
    \tau: 246
    \textbf: 49
    \textcircled: 376
    \textit: 291
    \textnormal: 10
    \textrm: 438
    \textsf: 136
    \textstyle: 16
    \texttt: 359
    \textup: 177
    \theta: 413
    \thicklines: 253
    \thinspace: 165
    \tilde: 334
    \times: 102
    \tiny: 72
    \to: 56
    \top: 13
    \triangle: 471
    \triangleleft: 410
    \triangleright: 254
    \tt: 119
    \unboldmath: 420
    \underbrace: 381
    \underline: 430
    \unitlength: 318
    \uparrow: 278
    \uppercase: 440
    \upsilon: 115
    \varepsilon: 274
    \varphi: 74
    \varpi: 481
    \varrho: 131
    \varsigma: 159
    \vartheta: 415
    \vcenter: 234
    \vdash: 470
    \vdots: 469
    \vec: 18
    \vector: 286
    \vee: 256
    \verb: 271
    \vert: 106
    \vline: 236
    \vphantom: 150
    \vrule: 107
    \vskip: 65
    \vspace: 121
    \vss: 219
    \wedge: 203
    \widehat: 436
    \widetilde: 73
    \wp: 366
    \xi: 89
    \zeta: 319
    \{: 39
    \|: 75
    \}: 156
    ']': 490
    ^: 355
    _: 215
    '`': 195
    a: 94
    b: 509
    c: 140
    d: 84
    e: 148
    f: 443
    g: 323
    h: 370
    i: 257
    j: 202
    k: 213
    l: 333
    m: 101
    n: 503
    o: 25
    p: 230
    q: 133
    r: 280
    s: 445
    t: 502
    u: 518
    v: 284
    w: 394
    x: 500
    y: 373
    z: 362
    '{': 186
    '|': 351
    '}': 103
    '~': 496
